### ISSUE TITLE
How does this compare to Horizonstate?

### ISSUE THREAD

**Issue by lucrus73** [the-laughing-monkey/cicada-platform#14]
It seems they are ages ahead: [https://horizonstate.com/](https://horizonstate.com/)

**Comment by nimbosa** [comment]
is Horizon State an open source project? looks like they arev private & proprietary? @lucrus73

**Comment by lucrus73** [comment]
> is Horizon State an open source project? looks like they arev private & proprietary? @lucrus73

Well, back when they launched the dApp, or sometime after, I had a chat session with someone of the crew (I don't remember if it was Jamie Skella or someone else) and I was told HST was FOSS. I admit I didn't check the statement myself, I only believed the words, but you're right, just now I can't find the source code anywhere. Maybe I try to get in touch with them again and ask them.

**Comment by lucrus73** [comment]
I've just tried to recover my chat session from [slack.com](http://slack.com) only to find out the workspace has been deleted. Current HST site does not refer any chat channel anymore. I assume it's not FOSS anymore and maybe it has never been such. Closing.
